apiVersion: v1
kind: ConfigMap
metadata:
  name: app
  labels:
    app: app
data:
  logging-file-name: ./logs/spring-${HOSTNAME}.log
  spring-datasource-url: jdbc:mysql://mysql-0.mysql.default.svc.cluster.local/petclinic